Repository avaje/avaje-http, pull requests merged in 2025-01, with the labels that each got.

#543 Fix JsonB generic generation errors
  http-generator-core/src/main/java/io/avaje/http/generator/core/Append.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/JsonBUtil.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
  http-generator-core/src/test/java/io/avaje/http/generator/core/JsonBUtilTest.java
  tests/test-javalin-jsonb/src/main/java/org/example/myapp/web/test/GenericController.java
Labels: bug

#550 added support for Optional Request Parameters
  http-api/src/main/java/io/avaje/http/api/PathTypeConversion.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/ElementReader.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/TypeMap.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/UType.java
  tests/test-jex/src/main/java/org/example/web/myapp/WebController.java
Labels: enhancement

#553 [client] Support Generics with Jackson
  http-client/src/main/java/io/avaje/http/client/JacksonBodyAdapter.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientMethodWriter.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
  tests/pom.xml
  tests/test-client/pom.xml
  tests/test-client/src/main/java/example/github/Generic.java
  tests/test-client/src/main/java/example/github/GenericData.java
  tests/test-client/src/main/java/example/github/Repo.java
  tests/test-client/src/main/java/example/github/Simple.java
  tests/test-client/src/main/java/example/github/httpclient/GeneratedHttpComponent.java
  tests/test-client/src/main/java/example/github/httpclient/Simple$HttpClient.java
  tests/test-client/src/main/java/module-info.java
  tests/test-client/src/main/resources/META-INF/services/io.avaje.http.client.HttpApiProvider
  tests/test-client/src/main/resources/META-INF/services/io.avaje.http.client.HttpClient$GeneratedComponent
  tests/test-client/src/test/java/example/github/GithubTest.java
  tests/test-jex/src/main/resources/public/openapi.json
Labels: enhancement

#551 [client] Fully support package private
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientWriter.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentMetaData.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentReader.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/SimpleComponentWriter.java
  http-generator-client/src/test/java/io/avaje/http/generator/client/ComponentMetaDataTest.java
  http-generator-client/src/test/java/io/avaje/http/generator/client/clients/PrivateClient.java
  http-generator-client/src/test/java/io/avaje/http/generator/client/clients/PrivateClient2.java
  http-generator-client/src/test/java/io/avaje/http/generator/client/clients/other/PrivateClient2.java
  http-generator-core/src/main/java/io/avaje/http/generator/core/ProcessingContext.java
  tests/test-client-generation/src/main/java/org/example/pkgprivate/PrivateClient.java
  tests/test-client/src/main/java/example/github/pkgprivate/SimplePkgPrivate.java
  tests/test-client/src/main/java/module-info.java
  tests/test-client/src/main/resources/META-INF/services/io.avaje.http.client.HttpClient$GeneratedComponent
  tests/test-client/src/test/java/example/github/pkgprivate/PkgPrivateTest.java
Labels: enhancement

#557 [client] Breaking change - Rename @Client.Import(types=...) to @Client.Import(value=...). That is, rename types -> value
  http-api/src/main/java/io/avaje/http/api/Client.java
  http-generator-client/src/main/java/io/avaje/http/generator/client/ClientProcessor.java
  tests/test-client-generation/src/main/java/org/example/package-info.java
  tests/test-client-generation/src/test/java/org/example/CommonApiTest.java
Labels: API Change

#559 [client] Fix test generation overriding main components
  http-generator-client/src/main/java/io/avaje/http/generator/client/ComponentReader.java
  tests/test-client/src/test/java/example/github/Dummy.java
Labels: bug
